import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import ScrollToTopButton from "@/layouts/scrolltotop";
import OcrFooter from "@/layouts/ocrfooter";

// Load the Quicksand font
const quicksand = Quicksand({ subsets: ["latin"] });

// Metadata for SEO
export const metadata: Metadata = {
  title: "docsynecx - AI-Powered Document Processing",
  description: "Generated by create next app",
  icons: {
    icon: "/top-meta.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={quicksand.className}>
        {children}
        <ScrollToTopButton />
        <OcrFooter />
      </body>
    </html>
  );
}
